### ISSUE TITLE
useVueFuse not reevaluating list

### ISSUE THREAD

**Issue by studio-jw** [shayneo/vue-fuse#102]
## How to reproduce
1.  Set the initial value of the list to `null`
2. Update the value of the list to an array of items after 2 seconds

```js
const items = ref(null);
const { search, results } = useVueFuse(items?.value || []);

onMounted(() => {
    setTimeout(() => {
      items.value = ["John Doe", "Jane Smith"];
    }, 2000);
});
```

### Why an initial value of `null`?
Because it's very common to start with `null`, do an async API request to fetch some data, and set the data after the data is fetched.

## Expected behaviour
- The list in `useVueFuse` is updated to `["John Doe", "Jane Smith"]`

## Actual behaviour
- The list in `useVueFuse` is still `null`

Code sandbox: https://codesandbox.io/s/elegant-hugle-rjug8m?file=/src/App.vue

**Comment by shayneo** [comment]
Thanks for the codesandbox!

I write variables that start as `null` and get populated via fetch request all the time haha. I'll see if I can fix, feel free to take a crack at it and PR if you'd like!

**Comment by shayneo** [comment]
@studio-jw 4.1.1 should take care of this use case.

As now list can be a regular array or a null ref/computed that is mutated into an array.

**Comment by mwargan** [comment]
Fix works great - I think that under the same issue though, computed properties do not update (though refs do as expected now)
