### ISSUE TITLE
Quoted keys not searched 

### ISSUE THREAD

**Issue by nfunwigabga** [shayneo/vue-fuse#11]
It looks like quoted keys (e.g. "model":"model name") in the json object are not recognized. I'm using this with response from axios and search returns no results. Any thoughts?

**Comment by nfunwigabga** [comment]
ok this issue is resolved. The problem was from axios, not vue-fuse. Sorry for the mix.

**Comment by shayneo** [comment]
Glad you got it figured out 😄
