### ISSUE TITLE
Search result with filtered children?

### ISSUE THREAD

**Issue by iamvitali** [shayneo/vue-fuse#16]
Hi,
So if we have an array of objects and search for them, VueFuse returns the objects that match the criteria.
But if said objects have an array of children which we want to search, is it possible to filter those to the search criteria as well?

Examples:
```
[
	{
		label: 'parent123',
	},
	{
		label: 'parent321',
	}.
]
```

If we search for `parent123` we will get:
```
[
	{
		label: 'parent123',
	}
]
```

But if it's a group with children:
```
[
	{
		label: 'parent123',
		children: [
			{
				label: 'child1'
			},
			{
				label: 'child2'
			},
			{
				label: 'child3'
			},
		]
	},
...
```

Is it possible for a search of `parent123` to return back that object (as usual) but for a search of `child2` to get back:
```
[
	{
		label: 'parent123',
		children: [
			{
				label: 'child2'
			},
		]
	}
]
```
? :)

**Comment by iamvitali** [comment]
Or ... is this more of a request for https://github.com/krisk/Fuse/issues ?

Just realised this might be just a wrapper....

**Comment by shayneo** [comment]
@iamvitali - you're right in that this is just a wrapper implementation for vue. I think your question is better suited for the fuse team.

If fuse is able to support this, it would be through the `options` object, that you can pass into the `$search` method.

Closing for now!
