### ISSUE TITLE
Feature Request: Get search input via v-model prop

### ISSUE THREAD

**Issue by drdaemos** [shayneo/vue-fuse#18]
Right now, when the `defaultAll` option is `false`, you can't tell whether a search hasn't found any items or there was no search at all (input is blank). 
I think it would be quite convenient to get the current search input state via `v-model` prop on the `vue-fuse` component like this:

```
 <vue-fuse
              ...
              :defaultAll="false"
              v-model="inputState"></vue-fuse>
```

Alternatively, this data could also be a part of search updated event arguments, along with the search results.

P.S. Thank you for your work! vue-fuse really is a helpful fine component

**Comment by shayneo** [comment]
Thanks for the kind words, and for the suggestion! 

Would `inputState` just be a user defined property (maybe just a boolean) describing the inputState (`true` meaning that there is an input value, `false` meaning that the input value is blank?)

**Comment by nicooprat** [comment]
Having the same issue right now. I need to save the search term in the `$store`, is there any way to do it now? If not, `inputState` won't be enough in my case.

> Alternatively, this data could also be a part of search updated event arguments, along with the search results.

I'd rather this solution 👍 

Thanks!

**Comment by shayneo** [comment]
1.3.0 includes a new event, which is emitted when the value of the input is changed. The event is called `fuseInputChanged`, and you can pass in your own event name for this using the `inputChangeEventName` prop.

Hope that helps 😄
