### ISSUE TITLE
Throttle input

### ISSUE THREAD

**Issue by nicooprat** [shayneo/vue-fuse#19]
Is there any way to throttle input? I'm commiting to store when searching so it's doing a lot of mutations that pollute my history.

Didn't find anything here or at https://github.com/krisk/Fuse/search?q=throttle&type=Issues&utf8=%E2%9C%93.

Thanks!

**Comment by tetshi** [comment]
Seems like you could easily use lodashs debounce function (https://lodash.com/docs/4.17.4#debounce) to the watch property in the component src, then recompile and boom, good to go.

**Comment by nicooprat** [comment]
Sure, didn't want to increase bundle size by importing lodash or underscore though... Tried to copy/paste/adapt the function without success, don't know why. That was a bonus feature so I didn't spent too much time on it... Left it here in case someone succeed :)

**Comment by shayneo** [comment]
Lodash does a nice job of splitting up functions into individual packages, maybe we could try this solution with just the lodash.debounce module? https://www.npmjs.com/package/lodash.debounce

**Comment by tetshi** [comment]
I think that'd work fine, it wouldn't add much to it and it's pretty powerful. It'd definitely be a lot cheaper than rolling your own implementation I think if you consider the time savings.

**Comment by nicooprat** [comment]
Didn't know that! I thought we had to rely on tree-shaking with Webpack or others. Don't have time to test it for know though.

**Comment by shayneo** [comment]
Closing as this is something that could be implemented using the `$search` method. Still open to PR if someone wants to add to the `VueFuse` component
