### ISSUE TITLE
Add style/class prop to customize css of input

### ISSUE THREAD

**Issue by SuperKiwi** [shayneo/vue-fuse#2]
Hey,
Thanks for this really nice package.
Would you be OK if I make a PR with style/class props on input ?

**Comment by shayneo** [comment]
Go for it! I considered adding this myself, but thought people might just want to handle styling in the parent component. Thanks!

**Comment by SuperKiwi** [comment]
Yep in fact you were right it is a bit useless. It is bettter to handle this in parent component.

**Comment by shayneo** [comment]
Absolutely. I think <div id="app"> is a remnant from my when I was testing the component locally. 

One idea I had was a few "out of the box" styles where you could use a prop to apply one of a few basic styles, or a "custom" option for full control. 

Would that be useful?

**Comment by SuperKiwi** [comment]
I have made a PR -> #4
