### ISSUE TITLE
Bind fuse value

### ISSUE THREAD

**Issue by nicooprat** [shayneo/vue-fuse#20]
I'm trying to bind my state to the fuse component value: I can filter my list, but if I select another category, I need to reset the search. So I tried to bind the value:

```js
<vue-fuse :search="search" :defaultAll="false" :keys="['key']" :list="items"/>
```

with my computed property:

```js
computed: {
  ...mapState(['search'])
}
```

when the route changes:

```js
router.afterEach(function(to, from, next) {
  store.state.search = ''
}
```

(The code is stripped to the bare minimum). Looks like the new search value is actually used (the list is back to its original state) but the `value` of the input doesn't change.

Looks like `search` isn't a `prop` in your component so I may be cheating a bit here... But I think it would be an interesting feature. Any way to do that?

I also tried to use the `$search` method but without success, plus it would be kind of dirty to do that at router-level...

Thanks.

**Edit:** Current workaround:

```js
computed: {
  search() {
    const search = this.$store.state.search
    const input = document.querySelector('[type="search"]')
    if (input) input.value = search
    return search
  }
}
```

**Comment by shayneo** [comment]
@nicooprat I just pushed a new version that emits an event whenever the value of the input text value is changed. I'm thinking this will let you keep track of that value a bit more elegantly. The default event name is `fuseInputChanged` but you can pass in your own event name to the new `inputChangeEventName` prop if needed.

Hope that helps!

**Comment by nicooprat** [comment]
The new event (and custom name) works, thanks. 

Is it possible to programmatically fire this event back with a parameter to trigger the search? My need is that I'm actually binding the search to an URL query parameter so I have to set it on page load, if the URL is like `/?search=test` for example.

That's why I think a prop binding would be easier :)

**Comment by shayneo** [comment]
gotchya!!! sorry for the misunderstanding.

I'd love to support this, but not sure when I'll be able to tackle it. Feel free to open a PR?

**Comment by nicooprat** [comment]
I'm just getting into Vue so I'll give it a try but can't guarantee anything :)

**Comment by shayneo** [comment]
All the more reason to give it a try!! No pressure though :)

**Comment by shayneo** [comment]
@voroncv requests to clear value in https://github.com/shayneo/vue-fuse/issues/22, this could be solved with prop binding
