### ISSUE TITLE
Set default value

### ISSUE THREAD

**Issue by MaffooBristol** [shayneo/vue-fuse#37]
I'd like to be able to prepopulate the `<vue-fuse>` component with a value, and have it automatically run the changed and input changed events, basically replicating what happens when a user types in a query, but done on page load.

I noticed you can do `value="testing..."`, but that doesn't allow for `:value`- also it seems to just be filling in the input but doesn't actually fire any events.

There's the `$search` method, but that doesn't seem to be connected with the component version.

Any ideas?
Thanks

**Comment by MaffooBristol** [comment]
I managed to get the functionality I wanted using a gross, hacky solution. I'd rather be able to do it properly, but this is what I have so far...

```javascript
export default {
  methods: {
    populateFromParams: function () {
      const params = this.parseParams(this.$route.params.args);
      // Set the value that vue-fuse would normally populate on text input.
      this.keyword_input = params.keywords;
      // Get the input DOM element.
      const element = this.$el.querySelector('.keywords-search');
      // Create an input event.
      const event = document.createEvent('HTMLEvents');
      event.initEvent('input', true, true);
      // Set the value of the element to match our populating value.
      element.value = params.keywords;
      // Trigger the input event, to force a re-render.
      element.dispatchEvent(event);
    },
  },
};
```

**Comment by shayneo** [comment]
@MaffooBristol Sorry for the slow response!

This seems like a good idea, but I'm not 100% sure I'll have bandwidth to take on in the coming weeks. I'd be happy to review a PR if you're interested in adding this functionality! Feel free to add the appropriate prop/logic in https://github.com/shayneo/vue-fuse/blob/master/src/VueFuse.vue

**Comment by shayneo** [comment]
Closing as this can be achieved with the `$search` function instead of the `VueFuse` component. PR still welcome if someone wants to take it on.
