### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by taivu** [shayneo/vue-fuse#44]
Can we have a changelog? whats changed from v1.5.2 vs v2.0.2? A major version change to me indicates breaking changes, so I havent upgraded yet because Im not sure of the potential breaking changes.

**Comment by shayneo** [comment]
Good call - see here: https://github.com/shayneo/vue-fuse/releases/tag/2.0.0

**Comment by taivu** [comment]
regarding release notes: did you mean Vue CLI 3 or VinLi (https://github.com/vinli/vinli-cli#readme)?
