### ISSUE TITLE
Mobile bug

### ISSUE THREAD

**Issue by julienchazal** [shayneo/vue-fuse#46]
Hello,

There's a bug on your demo page using Chrome on Android 8.
Typing does not filter the list until you **focus out** of the search input.
I'm facing the same problem trying to use fusejs with Nuxt.
Any ideas ?

Thx !

**Comment by shayneo** [comment]
Hey! For this issue, I recommend using the `$search` method instead of the `VueFuse` component.  Something like this...
```
<template>
  <input type="text" v-model="searchTerm">Search</input>
</template>

<script>
  data () {
    return {
      searchTerm: '',
      results: []
    }
  },
  watch: {
    searchTerm () {
       this.$search(this.searchTerm, this.arrayToSearch, { keys: ['a', 'b', 'c'] }).then(results => {
          this.results = results
        })
    }
  }
</script>
