### ISSUE TITLE
npm install showing error

### ISSUE THREAD

**Issue by amirhkhadem** [shayneo/vue-fuse#51]
when trying to import I receive the following error: 

Could not find a declaration file for module 'vue-fuse'.

Try `npm install @types/vue-fuse` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-fuse';`ts(7016)

then i receive: 

```
npm install  @types/vue-fuse
npm ERR! code E404
npm ERR! 404 Not Found: @types/vue-fuse@latest

```

**Comment by shayneo** [comment]
sounds like a typescript issue. Happy to troubleshoot if you can provide more context/a sample project that replicated the issue.

Closing for now, but happy to re-open!

PS - sorry for the delay 🙀
