### ISSUE TITLE
Firefox finally is not a function issue when using vue-fuse

### ISSUE THREAD

**Issue by tomchi89** [shayneo/vue-fuse#52]
I have noticed recently in several Vue projects that when I imported this library it was a cause of breaking polyfills in Firefox (latest version). 

Projects were run with Vue CLI either with a standard default configuration or custom. Both situation I was ending up with:

TypeError: "this.testPromise(...).then(...).finally is not a function" error. 

I'm raising this issue in a case if someone else is wondering why Vue app stopped working on FF after importing this plugin. 

I haven't got a chance yet to dig into the source and see what is actually causing that Firefox can't handle promises anymore so if someone will have spare time and help fix it I think much people will appreciate that.

**Comment by shayneo** [comment]
can you provide a sample project that replicates the issue? I use in multiple vinli-cli projects and firefox works great!

Closing for now, but happy to reopen
