### ISSUE TITLE
Error compiling in Quasar Framework

### ISSUE THREAD

**Issue by Paperasse** [shayneo/vue-fuse#6]
I'm using the Quasar Framework and installed vue-fuse correctly with npm.

Getting this error message after running "npm run dev":

 error  in ./~/vue-fuse/src/VueFuse.vue

Module build failed: Error: Couldn't find preset "env" relative to directory "D:\\Documenten\\My Web Sites\\Quasar-Paperasse\\node_modules\\vue-fuse"
    at D:\Documenten\My Web Sites\Quasar-Paperasse\node_modules\babel-core\lib\transformation\file\options\option
-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (D:\Documenten\My Web Sites\Quasar-aperasse\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
.....

**Comment by shayneo** [comment]
@Paperasse I'm not familiar with the Quasar Framework. Would you mind creating a project that replicates the error that I can fork?

**Comment by Paperasse** [comment]
I have made on my machine a Quasar App with VueFuse. I'm new to github. How do  I upload the files to the project I created on GitHub

**Comment by Paperasse** [comment]
Find my project here: [https://github.com/Paperasse/Quasar-VueFuse.git]

**Comment by shayneo** [comment]
@Paperasse thanks for providing the sample project, I was able to replicate the issue and found a fix! Check out this issue regarding `babel-preset-es2015` dependency: [LINK](https://github.com/babel/babel-preset-env/issues/186)

I ran `npm install babel-preset-env --save-dev` and was able to get the project to build

**Comment by Paperasse** [comment]
Thanx,

I will run the command and let you know the result

Met vriendelijke groet,
Henk Feijt

**Comment by Paperasse** [comment]
It works. Thanx

**Comment by Paperasse** [comment]
I don't know wether this is the proper way to ask for a feature. I would like to able to the input of the framework I am using, rather have vue-fuse render a input which is not in line with the other inputs. I think it could be done by making the search a property. Vue-fuse would then only focus on searching the data.

Kind regards,
Henk Feijt

**Comment by shayneo** [comment]
@Paperasse thanks for the request, I tried to summarize in the new issue. https://github.com/shayneo/vue-fuse/issues/8

If you want to take a stab at this, feel free to submit a pull request!

Also, feel free to comment on the new issue if you have additional suggestions for the design of what you are looking for.

**Comment by Paperasse** [comment]
I have cloned the vuefuse repro and made the necessary modifications and it works. Have altered the demo to use vuetify. I will create a repro in my account and git the demo project to the repro.

Met vriendelijke groet,
Henk Feijt
