### ISSUE TITLE
Document search prop

### ISSUE THREAD

**Issue by JoshMoreno** [shayneo/vue-fuse#68]
The search prop is undocumented and you have to dig through the source code or issues to figure out how to do something like clear the input.

Here's a simple example of how one could manage the search input's value. For anyone wanting to understand, the `vue-fuse` initializes the inputs value with the value of the `search` prop. It then watches the `search` prop and whenever it changes, it sets the input's value to the new value of `search`.

```vue
<template>
    <div>
        <vue-fuse 
            ...
            @fuseInputChanged="search = $event"
            :search="search"
        ></vue-fuse>
        <button @click="search = ''" type="button">Clear search</button>
    </div>
</template>

<script>
export default {
    data() {
        return {
            search: '',
        }
    }
}
</script>

```

**Comment by shayneo** [comment]
I'm planning a new major version release, as we're several major versions behind Fuse.js latest. I'll try to provide more info on this functionality in the new release
