### ISSUE TITLE
Changing options on the fly?

### ISSUE THREAD

**Issue by joonaspaakko** [shayneo/vue-fuse#69]
The issue is that I can't seem to change at least `keys` and `shouldSort` after vue-fuse is mounted. Or maybe I'm just doing it wrong.

> Overall I don't think this is a big issue. The biggest pain I had was when I needed to change `shouldSort` when the search input was focused (a very convoluted thing, not important...). Because I then had to re-render vue-fuse to give it the new setting, the search input focus would obviously be lost and I had to steal back the focus. It worked, but it just felt like a super roundabout way to do it. Otherwise, I didn't really have any issues re-rendering vue-fuse.
____

`list` seems to update just fine but for seemingly everything else I need to re-render the component to apply the new settings. 

Here's a [codesandbox example](https://codesandbox.io/s/vue-fuse-changing-options-by-re-rendering-the-the-component-0zvt8?file=/src/App.vue:88-207) where I'm changing `keys` (doesn't work without re-render) and `list` (no need to re-render). 

A here's a smaller example:

```html
<VueFuse v-if="searchEnabled" :shouldSort="shouldSort">

<label>
  <input type="checkbox" v-model="shouldSort" @change="updateSearch()" />
  should sort
</label>
```

```js
data: function() {
  return {
    searchEnabled: true,
	shouldSort: true,
  }
},
methods: {
  updateSearch: function () {
    this.searchEnabled = false;
    this.$nextTick(() => {
      this.searchEnabled = true;
    });
  },
},
```

**Comment by insign** [comment]
Are you using the component or the function?

**Comment by shayneo** [comment]
hmmm wonder if adding a watcher to the options to kick off a re search might help?

**Comment by joonaspaakko** [comment]
@insign, I updated the first post. 

@shayneo, I'm not sure... At the time I was pretty much in a `I just need to get this done, I don't care how stupid it is` mode and re-rendering the component seemed to solve it without it becoming a big issue. Since then I've decided to use vue.js directly, so as far as I'm concerned the issue can be closed.

**Comment by shayneo** [comment]
closing this, but 3.0 should handle this kinda thing much more elegantly. See here:
https://github.com/shayneo/vue-fuse/commit/342553da4cde6eaae54e7ecd742ecdc031768945
