### ISSUE TITLE
Removing the "X" in the input

### ISSUE THREAD

**Issue by austintoddj** [shayneo/vue-fuse#71]
Hey! Love the package, really great. The one question I had however is if you know of a way to remove the "X" that's visible when you hover over the input when some text has been added? 

<img width="836" alt="Screen Shot 2020-06-27 at 7 36 25 PM" src="https://user-images.githubusercontent.com/8037011/85934788-b55f5c00-b8ad-11ea-96ac-3346e5207e18.png">

**Comment by shayneo** [comment]
At first glance it looks like there is some outside css styling the input. This package doesn’t ship any css styling, so it should just give you the native browser input tag and behavior.

Hope that helps!

**Comment by austintoddj** [comment]
Hm yeah you’re right, I did some style things to it. Now I’m even more confused since I’m the culprit 😅 Thanks for the help, keep up the good work!
