### ISSUE TITLE
Fuse extended search not working

### ISSUE THREAD

**Issue by crawazaky** [shayneo/vue-fuse#74]
Hello,

i am trying to use the useExtendedSearch option with vue-fuse but I dosen't seem to work.

I am setting up my options like this:
```
      searchOptions: {
          includeScore: true,
          useExtendedSearch: true,
          defaultAll: false,
          // Search in `author` and in `tags` array
          keys: ['searchable.name']
        }
```

and running my search like this:

```
        this.$search(this.searchQuery, this.searchList, this.searchOptions)
        .then(results => { })
```

If I do something like ```!keyword``` it still show me entries with ```keyword```in its ```searchable.name```.

Is there something wrong with my code, or is vue-fuse not supporting this option ?

Thanks a lot

**Comment by shayneo** [comment]
Looks like Fuse.js has been adding features and incrementing major versions very rapidly! Looks like the `useExtendedSearch` option isn't available in the Fuse.js version that we are using (`^3.4.6`). 

I'll look to update fuse and do a major version bump on this lib soon!
