### ISSUE TITLE
Vue 3 Compatibility

### ISSUE THREAD

**Issue by benjaminye** [shayneo/vue-fuse#77]
Hi,

Does this plugin support Vue 3? I'm having some problems loading the plugin.

Thanks,
Ben

### Import Statement
```
import { createApp } from "vue";
import App from "./App.vue";
import VueFuse from "vue-fuse";

createApp(App)
  .use(VueFuse)
  .mount("#app");
```

### Error Message
![image](https://user-images.githubusercontent.com/17937357/101418631-41919880-38bc-11eb-8d0b-8a412443be15.png)

**Comment by shayneo** [comment]
no yet!
You might try importing the component directly to parent component and registering it there... something like:
```
import VueFuse from "vue-fuse/src/components/VueFuse.vue"

export default {
  components: {
    VueFuse
  }
  // ...
}
```

not sure if that will actually work though ;)

**Comment by benjaminye** [comment]
Thanks for the reply! I tried importing it as a component -- and it worked!
Though I really only need the instance method for prototyping. I guess I'll use the vanilla fuse.js for now. 

Merry Christmas!

**Comment by shayneo** [comment]
Thanks for trying @benjaminye ! hopefully this helps others wanting to use the component in a vue-3 project. The instance method is a very straight forward wrapper of vanilla fuse.js, so I'd say you're on the right track.

Cheers and Merry Christmas! 🎄✝️🌟
