### ISSUE TITLE
Feature Request: Support a "method only" implementation

### ISSUE THREAD

**Issue by shayneo** [shayneo/vue-fuse#8]
See issue https://github.com/shayneo/vue-fuse/issues/6#issuecomment-306548917

The request is to have an option not to access the fuse logic via the `input` component, but as a standalone method that could be added as a mixin?

something like:
```
methods: {
  runSearch () {
    vuefuse.search(keys, list)
  }
}
```

**Comment by Paperasse** [comment]
I have cloned the vuefuse repro and made the necessary modifications and it works. Have altered the demo to use vuetify. I will create a repro in my account and git the demo project to the repro. It is different approach then you suggest. Vuefuse no longer renders an input field. Wil provide a link to the repro. I will also make a demo with the Quasar Framework.

**Comment by shayneo** [comment]
@Paperasse that's great! thanks

I'll take a look and see if I can pull in/fork your repo into a feature.

I still like the approach of giving the input, but think that your approach is valuable as well. Ideally, I'd like to configure the package so that both options are available

**Comment by Paperasse** [comment]
Working on it. To not break the code for those who already use the component the input will stay available. Have this in working order. There is a switch which shows/hides the input by using v-if in the input.

Met vriendelijke groet,
Henk Feijt

**Comment by Paperasse** [comment]
I got it working. It was actually pretty easy. Added a method runSearch which just uses existing functionality. Refactored the component to avoid duplicate code. The solution is to add a reference to the vuefuse tag f.i, "vuefuse". This reference is then used to call the new method.: this.$refs.vuefuse.query(searchText).

I think it makes vuefuse more feasible and apealling. More scenario's are possible to implement.

Tried to push the project with the new destop github app. Thought had succes, but not yet. Try again tomorrow. Will provide link to repository after succes.

**Comment by Paperasse** [comment]
Didn't manage to upload to github. So I included a zip or the project. Hope you can work with that.

[vuefuse-vuetify-demo.zip](https://github.com/shayneo/vue-fuse/files/1065662/vuefuse-vuetify-demo.zip)

**Comment by shayneo** [comment]
@Paperasse sorry for the delay on this, been busy!! I've downloaded the project and will take a look. Hopefully I can open up a new branch in the next few days and get your input 😄

**Comment by iamvitali** [comment]
:pray:

**Comment by shayneo** [comment]
@iamvitali in progress. expect a new release within a few days! (maybe tonight)

**Comment by shayneo** [comment]
This has been added to release 1.2.0! use `$search` method, like this:
```
this.$search(this.term, this.bikes, this.options).then(results => {
  this.searchResults = results
})
```

more doc sin the readme
